apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-api-configmap
data:
  API_PORT: "8080"
spec:
  template:
    spec:
      containers:
        env: 
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap
                key: API_PORT
