api: apps/v1
kind: deployment
metadata:
  name: synergychat-api
  lables:
    app: synergychat-api
specs:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    specs:
      containers:
       - name: synergychat-api
         image: bootdotdev/synergychat-api:latest